---
# Purpose: Download and install zookeeper on all master servers
#
# Notes:
#   - Executed only on nodes belonging to group masters
#   - Installs also the Hadoop related tarballs etc.

- name: Create Hadoop related directories
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group=hadoop
    mode={{ item.mode }}
    recurse=yes
    state=directory
  with_items:
    - { path: '{{ ZOOKEEPER_CONFIG }}', owner: 'zookeeper', mode: 775 }
    - { path: '{{ VAR_RUN_BASE }}/zookeeper/logs', owner: 'zookeeper', mode: 775 }
    - { path: '{{ VAR_RUN_BASE }}/zookeeper/pid', owner: 'zookeeper', mode: 775 }
    - { path: '{{ ZOOKEEPER_DATA }}', owner: 'zookeeper', mode: 775 }

- name: Download Zookeeper
  get_url:
    url={{ ZOOKEEPER_DOWNLOAD_LINK }}/zookeeper-{{ ZOOKEEPER_VERSION }}/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
    dest=/tmp/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
    mode=0644
  when: REMOTE_FETCH_TARBALLS == true

- name: Untar Zookeeper
  unarchive:
    src=/tmp/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
    dest={{ PACKAGE_BASE }}
    owner=zookeeper
    group=hadoop
    copy=no
    creates={{ PACKAGE_BASE }}/zookeeper-{{ ZOOKEEPER_VERSION }}
  when: REMOTE_FETCH_TARBALLS == true

- name: Untar Zookeeper
  unarchive:
    src=files/downloads/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
    dest={{ PACKAGE_BASE }}
    owner=zookeeper
    group=hadoop
    copy=yes
    creates={{ PACKAGE_BASE }}/zookeeper-{{ ZOOKEEPER_VERSION }}
  when: REMOTE_FETCH_TARBALLS == false

- name: Symlink Zookeeper
  file:
    src={{ PACKAGE_BASE }}/zookeeper-{{ ZOOKEEPER_VERSION }}
    path={{ ZOOKEEPER_HOME }}
    owner=zookeeper
    group=hadoop
    state=link

- name: Put Zookeeper configuration in place
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=zookeeper
    group=hadoop
    mode=0644
  with_items:
    - { src: "etc/zookeeper/zoo.cfg.j2", dest: "{{ ZOOKEEPER_CONFIG }}/zoo.cfg" }
    - { src: "etc/zookeeper/log4j.properties.j2", dest: "{{ ZOOKEEPER_CONFIG }}/log4j.properties" }
    - { src: "etc/zookeeper/jaas.conf.j2", dest: "{{ ZOOKEEPER_CONFIG }}/jaas.conf" }
    - { src: "etc/zookeeper/java.env.j2", dest: "{{ ZOOKEEPER_CONFIG }}/java.env" }
    - { src: "data/zookeeper/myid.j2", dest: "{{ ZOOKEEPER_DATA }}/myid" }

- name: Template Systemd scripts
  template: src=etc/systemd/system/{{ item.src }} dest=/etc/systemd/system/{{ item.dest }} owner=root group=root mode=755 backup=yes
  with_items:
    - { src: "zookeeper.service.j2", dest: "zookeeper.service" }
