---
galaxy_info:
  author: Derek Carter
  description: EPEL repository 
  company: Goozbach Infrastucture Solutions LLC
  license: GPLv2 or MIT
  min_ansible_version: 1.3
  categories:
    - packaging
  platforms:
    - name: EL
      versions:
        - 7
        - 6
        - 5
dependencies: []
